Repository pescadores/pescador, pull requests merged in 2019-07, with the labels that each got.

#145 [RFC] bugfix ShuffledMux with integer weights
  pescador/mux.py
  setup.py
  tests/test_mux.py
Labels: bug

#146 Expanded buffer_stream docs
  pescador/maps.py
Labels: Documentation

#150 Remove deprecated `Mux` and add Streamer conversion
  pescador/core.py
  pescador/mux.py
  tests/test_mux.py
Labels: API, enhancement

#151 Decorator interface
  README.md
  pescador/core.py
  tests/test_core.py
Labels: API, enhancement
